name: OWASP ZAP

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run OWASP ZAP scan
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        
        # Make sure OWASP ZAP is accessible
        export PATH=$PATH:\Program Files\ZAP\Zed Attack Proxy

        # Run OWASP ZAP scan
        zap-cli --zap-path \Program Files\ZAP\Zed Attack Proxy --quick-scan http://localhost:3000
